### ISSUE TITLE
Transfer data from Danforth using Globus

### ISSUE THREAD

**Issue by max-zilla** [terraref/computing-pipeline#120]
In order to make Danforth data available in the globus directories on Roger and thus accessible similar to the UA-MAC data, we will modify @nfahlgren script to transfer files to Roger using Globus.

Steps involved:
- Set up Globus endpoint at Danforth with access to correct data directories
- Modify script that currently sends via Clowder API to send via Globus
  - Globus has a python API: https://github.com/globusonline/transfer-api-client-python
  - metadata can be included in the transfer
  - final step is to notify my Roger Monitor that a Globus transfer has begun. I will show you how to do this.
- On Roger, my monitor will track the Globus transfer until it is done and create Clowder datasets/collections as needed.

My script that handles this in Arizona is here:
https://github.com/terraref/computing-pipeline/blob/master/scripts/gantrymonitor/gantry_monitor_service.py
...but this has a lot of stuff we won't need here. 

I'll need to make sure my monitor on Roger is able to correctly create datasets given differences between MAC data (which is all it handles right now) and Danforth data.

@nfahlgren we will work together to get this written.

**Comment by nfahlgren** [comment]
@max-zilla Globus is running on our head node. I have a configured endpoint (ddpscbioinfo#apollo) that we can use.

**Comment by max-zilla** [comment]
@nfahlgren to get this started, ill create a branch with a version of your script that implements some Globus pieces, specifically the part that communicates with my Roger monitor (so I can make sure the Roger monitor is prepared to receive info from Danforth in addition to MAC). hopefully I can get a first version of that done today.

**Comment by max-zilla** [comment]
@nfahlgren some discussion with @robkooper this morning. We plan on deploying your PlantCV extractor that @yanliu-chn is working on that we can use to demonstrate the functionality next week, whether on the dev instance of clowder or the production depends on when clowder master branch is updated. 

You will use your current script to transfer the files for that - I'm working on the Globus updates, we came up with a way to avoid modifying your code so much. The idea is that we will deploy a version of the Globus transfer monitor currently deployed at MAC, which reads off FTP files. We won't use the FTP scanning component, but we can use the lightweight API I've implemented for it.

Basically, you can just POST a list of files to the monitor ip (default 0.0.0.0:5455/files) and the monitor will automatically initiate Globus transfers with the configured account+credentials every few minutes. The ROGER monitor will be notified and watch the Globus transfer until it is done - at this point at MAC, we create a symlink to the transferred file in a /deleteme folder for deletion later. We could do something similar with your code as well.

Action items for me are to review my monitors, which are somewhat complex, and make sure it's generic where it needs to be. In particular I'll need to adjust how datasets are created, as they expect MAC-specific file and path structures right now. Shouldn't be a problem, but again I won't be trying to deploy this before next Wednesday.

Will follow up when I have updates on this or the PlantCV dataset extractor.

**Comment by max-zilla** [comment]
https://github.com/terraref/computing-pipeline/tree/Danforth-PlantCV-globus-mods/scripts/plantcv 
Here is the branch I'm working on, by the way.

Yesterday it sounds like @fwang29 and @yanliu-chn got the updated PlantCV extractor working, it's being tested now so hopefully we'll be able to deploy in the next day or two.

**Comment by nfahlgren** [comment]
@max-zilla sounds good. Right now we have a webservice that is used to extract data from the LemnaTec database (postgreSQL). The uploader code I have reads the exported directory and metadata file from this service. The plan is to replace this webservice with a monitor that watches the database and automatically exports data to our bioinformatics cluster (and triggers an upload to NCSA when necessary).

**Comment by max-zilla** [comment]
@nfahlgren I've made progress on my branch. the changes for the monitor ended up being a bit more substantial due to folder structure weirdness, but I think I have a script ready. I need to test my updates more before we stand it up, however.

https://github.com/terraref/computing-pipeline/tree/support-climate-logs
This branch adds a lot of generic code to support new folder structures at a site level - essentially we built this with LemnaTec/MovingSensors as the primary directory but now there's a MAC in addition to LemnaTec, and soon to be Danforth. Had to overhaul some things I haven't tested yet.

Then I'll merge the globus mods for your upload piece and will follow up so we can deploy.

**Comment by nfahlgren** [comment]
@max-zilla sounds good, let me know is you need to run any tests from the DDPSC. You have a user account right and/or would that be useful?

**Comment by max-zilla** [comment]
@nfahlgren for Globus, i think it would make sense to have a Danforth-specific user. This allows me to upload incoming files as different Clowder users, for instance (e.g. a Danforth user vs. a MAC user) and generally helps us partition things.

Up to this point I've been transferring data from MAC as my Globus account maxzilla, but I think we want to do the same with MAC as well (a dedicated user).

This might mean adjustment of permissions from @jdmaloney but not sure about that.

**Comment by rachelshekar** [comment]
@jdmaloney  - are we receiving this data?  Can this issue be closed?

**Comment by max-zilla** [comment]
We cannot close this. Now that the extractor is deployed I'll work on this.

**Comment by max-zilla** [comment]
@nfahlgren I am troubleshooting the PlantCV extractor right now. The tests worked locally on a couple snapshots, but now that I've deployed and let it run on a couple datasets in production I'm seeing:

```
...processing: VIS_TV_z1_h0_g0_e110_1124066.png + NIR_TV_z1_h0_g0_e50_1124075.png
...uploading resulting metadata
...processing: VIS_SV_0_z1_h1_g0_e82_1124058.png + NIR_SV_0_z1_h1_g0_e35_1124067.png
...uploading resulting metadata
...processing: VIS_SV_180_z1_h1_g0_e82_1124062.png + NIR_SV_180_z1_h1_g0_e35_1124071.png
...uploading resulting metadata
...processing: VIS_SV_270_z1_h1_g0_e82_1124064.png + NIR_SV_270_z1_h1_g0_e35_1124073.png
...uploading resulting metadata
...processing: VIS_SV_90_z1_h1_g0_e82_1124060.png + NIR_SV_90_z1_h1_g0_e35_1124069.png
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyclowder/extractors.py", line 346, in thread_function_dataset
    _processFileFunction(jbody)
  File "terra.plantcv.py", line 171, in process_dataset
    vn_traits = pcia.process_sv_images_core(vis_id, img, nir_id, nir, nir2, traits)
  File "PlantcvClowderIndoorAnalysis.py", line 384, in process_sv_images_core
    device, obj, mask = pcv.object_composition(vis_img, roi_objects, hierarchy3, device, debug)
  File "/home/ubuntu/plantcv/lib/plantcv/object_composition.py", line 31, in object_composition
    group = np.vstack(contours[i] for i in ids)
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

I'm trying to figure out what's throwing this error on nx.concatenate, but figured I'd post it here in the meantime in case you've seen this before. The filenames look to match up properly and I didn't see anything that looked obviously unusual when I looked at the input variables for
```
vn_traits = pcia.process_sv_images_core(vis_id, img, nir_id, nir, nir2, traits)
```

**Comment by nfahlgren** [comment]
@max-zilla I think it's a "normal" failure, probably because there was no plant in the image or another processing problem. I looked up that image and confirmed that the plant is very small and was probably missed in one of the angles. We try to catch these failures but are obviously still missing checks in some places, does this create problems with the pipeline?

**Comment by max-zilla** [comment]
@nfahlgren that's actually a bit of a relief. I can add some try/catch messages for now, and we can maybe indicate them somehow in the outputs (certainly the logs). 

The 2014 pilot data was transferred and is now standing by to go through the extractor, so I'll get this cleaned up and try it again. Thanks for the quick feedback.

**Comment by nfahlgren** [comment]
Thanks @max-zilla

**Comment by max-zilla** [comment]
@nfahlgren I didn't end up changing anything in your PlantcvClowderIndoorAnalysis code, but I added a try/catch to my terra.plantcv.py extractor code. Pseudocode:
```
try:
   vn_traits = pcia.process_sv_images_core()
except:
  print "...error generating vn_traits; no metadata uploaded"
```

I ran this on the specific trouble dataset and it handled most of the SV images fine, just the 90 image that was problematic. avg_traits.csv still looks fine. I'm going to push this update for now and see if that lets us proceed - we can come up with a cleaner solution down the road if we need to.

**Comment by max-zilla** [comment]
@gsrohde I am getting a 400 error on the BETYdb upload:

```
/home/extractor/sites/danforth/Level_1/plantcv/ddpscIndoorSuite - 2014-06-05__16-50-49-828/avg_traits.csv
Error uploading CSV to BETYdb 400
{
  "metadata": {
    "URI": "https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv?key=OMITTED",
    "timestamp": "2016-10-19T08:48:18-05:00"
  },
  "errors": {
    "schema_validation_errors": [
      [
        "You can't specify a treatment without specifying a citation."
      ]
    ]
  }
}
```

In this issue it sounded like citation was optional: 
https://github.com/terraref/computing-pipeline/issues/33

...but we are including treatment so it seems I need it. The CSV contents:
```
entity,cultivar,treatment,local_datetime,sv_area,tv_area,hull_area,solidity,height,perimeter,access_level,species,site
Fp001AB006772,BTx642,80%: 173.6 ml water (37.5% VWC),2014-06-05T16:50:49.828,590.666666667,796.0,639.5,0.897150687152,56,169.047319849,2,Sorghum bicolor,Danforth Plant Science Center Bellweather Phenotyping Facility
```

Treatment = "80%: 173.6 ml water (37.5% VWC)" can you assist in what citation would correspond to this? If the citation will be the same across all these pilot datasets, I can update my extractor quickly. I've stopped it for now.

**Comment by dlebauer** [comment]
@max-zilla this citation
https://terraref.ncsa.illinois.edu/bety/citations/6000000003

**Comment by max-zilla** [comment]
@dlebauer @gsrohde thanks. Added these fields to avg_traits.csv outputs:

```
citation_author,citation_year,citation_title
"Fahlgren, Noah",2016,Unpublished Data from Sorghum Test Runs
```

I'll give this a try.

**Comment by max-zilla** [comment]
@gsrohde @dlebauer 

The code when I developed the extractor (and I believe successfully tested) was generating:
```
"local_datetime": "2014-06-03T14:11:25.312"
ERROR
"You can't have a local_datetime attribute on a trait-group's defaults element if the default site doesn't specify a time zone."
```

...so OK, I'll add the time zone to each record in that case (not sure if we intended for site to have a time zone).
```
"local_datetime": "2014-06-03T18:04:42.046-05:00"
ERROR
"Element 'trait', attribute 'local_datetime': '2014-06-03T18:04:42.046-05:00' is not a valid value of the union type 'local-datetime'.",
```

I could use python to convert this to UTC time, but perhaps this represents a problem in BETY that should be fixed. 

The extractor was working otherwise: https://terraref.ncsa.illinois.edu/clowder/datasets/58062c2d4f0caeb1e4afe506
(not the most interesting example because there wasn't enough plant to generate any avg_traits here, so it shows -1)

**Comment by gsrohde** [comment]
@max-zilla It's the _site_ that needs a time zone, not `local_datetime`.

The time zone name for Danforth should be `America/Chicago`.

You are correct that there is no way to edit the time zone in the UI.  (Perhaps I should add the timezone table I used to populate this column on ebi-forecast and have it set automatically from the geometry when a new site is created.)

**Comment by max-zilla** [comment]
@gsrohde is it possible update that record in the database directly? if so, would you be so kind?

**Comment by gsrohde** [comment]
@max-zilla Done.

**Comment by max-zilla** [comment]
```
INFO    : pyclowder.extractors -  Starting a New Thread for Process Dataset
...processing: VIS_TV_z1_h0_g0_e110_1128276.png + NIR_TV_z1_h0_g0_e50_1128285.png
...uploading resulting metadata
...processing: VIS_SV_0_z1_h1_g0_e82_1128268.png + NIR_SV_0_z1_h1_g0_e35_1128277.png
...uploading resulting metadata
...processing: VIS_SV_180_z1_h1_g0_e82_1128272.png + NIR_SV_180_z1_h1_g0_e35_1128281.png
...uploading resulting metadata
...processing: VIS_SV_270_z1_h1_g0_e82_1128274.png + NIR_SV_270_z1_h1_g0_e35_1128283.png
...uploading resulting metadata
...processing: VIS_SV_90_z1_h1_g0_e82_1128270.png + NIR_SV_90_z1_h1_g0_e35_1128279.png
...uploading resulting metadata
...output file: /home/extractor/sites/danforth/Level_1/plantcv/ddpscIndoorSuite - 2014-06-06__13-13-02-406/avg_traits.csv
/home/extractor/sites/danforth/Level_1/plantcv/ddpscIndoorSuite - 2014-06-06__13-13-02-406/avg_traits.csv
https://terraref.ncsa.illinois.edu/bety/api/beta/traits.csv?key=GZJZWnJpnDBhmKk7k6vb46z6lW6vjxSniRivRl2I
CSV successfully uploaded to BETYdb.
"Metadata successfully added to db"
```

https://terraref.ncsa.illinois.edu/clowder/datasets/58062c2f4f0caeb1e4afe57a

Looks like we're in business!

**Comment by dlebauer** [comment]
@max-zilla can this be documented and closed?

**Comment by max-zilla** [comment]
@dlebauer yes, we can close. The final Danforth Globus piece is finishing up discussion here: https://github.com/terraref/computing-pipeline/issues/136

I'll move pertinent discussion from here to the README on the extractor.
