### ISSUE TITLE
'readlink -f' in computing-pipeline/scripts/hyperspectral/terraref.sh 

### ISSUE THREAD

**Issue by yanliu-chn** [terraref/computing-pipeline#134]
terraref.sh has two places using `readlink` to get the full path to scripts. i think the correct argument is `readlink -f /path/to/fileordir`. could you check and make a quick fix to the master branch?

**Comment by czender** [comment]
Are you sure "readlink -f" is portable between Linux and Mac? I would like to preserve Mac/Linux portability and I think "-f" means something different on Mac (=BSD) than Linux, and readlink without the "-f" appears to work on both.

**Comment by yanliu-chn** [comment]
I see. I dug a bit to find the diff b/w linux and mac, and with and without -f. I tested CentOS on ROGER and Unbuntu 14.04. My laptop is mac. 

On both platforms, without -f, if we readlink a symbolic link, it returns the referenced path. if we readlink a non-symbolic link, it returns empty.
On linux, readlink -f returns the full path regardless the target is a symlink or not. 
On mac, -f means something different.

So my understanding is that readlink is used to get the full path to the script directory, right? or you just need readlink to resolve the symlink?

Without -f, terraref.sh failed on ROGER to get the location of scripts and exited with error.

**Comment by robkooper** [comment]
I use the following in one of my scripts (will not work on windows):

```
DIRNAME=$( dirname $0 )
python -c 'import os,sys;print os.path.realpath(sys.argv[1])' "${DIRNAME}/../.."
```

**Comment by czender** [comment]
@yanliu-chn yes, it's purpose is to get the path to script directory, since terraref.sh needs to call other scripts that will be in that directory. i will play with this until i find a solution that works on mac/linux with or without symbolic links (i happen to use symbolic links to run terraref.sh). am looking at solutions suggested here:
 http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
will post again when i have a new version of terraref.sh for you to pull to see if it works for you.

**Comment by yanliu-chn** [comment]
cool. thanks!

**Comment by czender** [comment]
@Zodiase and @FlyingWithJerome i committed a new version of terraref.sh intended to address the readlink issue. please pull and report any problems...

**Comment by yanliu-chn** [comment]
@czender , I tested the updated script. One more fix: it seems the module command used to load gdal stack and nco cleared BASH_SOURCE (after `module load` earlier). Is it possible to save BASH_SOURCE at the beginning?

**Comment by czender** [comment]
@yanliu-chn does this problem occur with the latest version?  i can move the BASH_SOURCE stuff to before the module stuff if necessary. please advise.

**Comment by yanliu-chn** [comment]
@czender , this issue is still there in the most recent version when running on ROGER (CentOS 6.7) where we will do production runs. It doesn't affect the Dockerfile because in the docker container, we don't use `module load`.

**Comment by czender** [comment]
@yanliu-chn i moved the check for script name to before the module command, so the issue should be fixed on Roger. please pull and verify when you have a chance.

**Comment by yanliu-chn** [comment]
@czender I verified that the change works now on ROGER. Please feel free to close the ticket. Thanks a lot!
